services:
  # backend:
  #   build: ./backend-service
  #   ports:
  #     - '8080:8080'
  #   restart: always
  #   depends_on:
  #     - migration
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_tracker
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SECURITY_JWT_SECRET_KEY: ${SECRET_KEY}

  migration:
    build: ./migration-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  postgres:
    image: postgres:14
    container_name: chore_tracker_db
    restart: always
    environment:
      POSTGRES_DB: chore_tracker
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
